spring.application.name=SGAE
server.port=8081

spring.datasource.url = jdbc:postgresql://localhost:5432/SGAEDb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.driver-class-name = org.postgresql.Driver
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto = update

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG



application.security.jwt.secret-key=voiciUneVraieCleBase64De32CaractdresMinimum1234567890AB


