spring.application.name=SGAE

spring.datasource.url = jdbc:postgresql://localhost:5432/autoDb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.driver-class-name = org.postgresql.Driver
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

application.security.jwt.secret-key=voiciUneVraieCleBase64De32CaractdresMinimum1234567890AB


